export const LOT_DETAILS = {
  data: [
    {
      travel_id: 1,
      owner_uid: "1",
      client_uid: "sqdsqdqsdqsd",
      status: "",
      active: true,
      price: 300,
      service: "Economique",
      company: "Nom de la compagnie",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip",
      lot: {
        delivry_start_date: "12/02/2020 18:29",
        delivry_end_date: "13/02/2020 19:20",
        starting_city: "Paris",
        starting_postal_code: 75013,
        starting_address: "1, rue de la fontaine à mulard",
        starting_access: "Plein pied",
        arrival_city: "Marseille",
        arrival_postal_code: 13000,
        arrival_address: "3, rue de la sainte",
        arrival_access: "Plein pied",
        size: 56,
        photo_url: "https://picsum.photos/100",
        distance: 1236,
      },
    },
    {
      travel_id: 2,
      owner_uid: "1",
      client_uid: "sqdsqdqsdqsd",
      status: "",
      active: true,
      price: 700,
      service: "Luxe",
      company: "Nom de la compagnie",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip",
      lot: {
        delivry_start_date: "12/02/2020",
        delivry_end_date: "18/02/2020",
        starting_city: "Bordeaux",
        starting_postal_code: 75013,
        starting_address: "1, rue de la fontaine à mulard",
        starting_access: "Plein pied",
        arrival_city: "Limoges",
        arrival_postal_code: 13000,
        arrival_address: "3, rue de la sainte",
        arrival_access: "Plein pied",
        size: 23,
        photo_url: "https://picsum.photos/400",
        distance: 1236,
      },
    },
    {
      travel_id: 3,
      owner_uid: "1",
      client_uid: "sqdsqdqsdqsd",
      status: "",
      active: true,
      price: 500,
      service: "Economique",
      company: "Nom de la compagnie",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip",
      lot: {
        delivry_start_date: "12/02/2020",
        delivry_end_date: "18/02/2020",
        starting_city: "Bruxelle",
        starting_postal_code: 75013,
        starting_address: "1, rue de la fontaine à mulard",
        starting_access: "Plein pied",
        arrival_city: "Toulouse",
        arrival_postal_code: 13000,
        arrival_address: "3, rue de la sainte",
        arrival_access: "Plein pied",
        size: 17,
        photo_url: "https://picsum.photos/300",
        distance: 1236,
      },
    },
    {
      travel_id: 4,
      owner_uid: "1",
      client_uid: "sqdsqdqsdqsd",
      status: "",
      active: true,
      price: 100,
      service: "Luxe",
      company: "Nom de la compagnie",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip",
      lot: {
        delivry_start_date: "12/02/2020",
        delivry_end_date: "18/02/2020",
        starting_city: "Saint-Ouen",
        starting_postal_code: 75013,
        starting_address: "1, rue de la fontaine à mulard",
        starting_access: "Plein pied",
        arrival_city: "Melun",
        arrival_postal_code: 13000,
        arrival_address: "3, rue de la sainte",
        arrival_access: "Plein pied",
        size: 44,
        photo_url: "https://picsum.photos/500",
        distance: 1236,
      },
    },
    {
      travel_id: 5,
      owner_uid: "1",
      client_uid: "sqdsqdqsdqsd",
      status: "",
      active: true,
      price: 420,
      service: "Luxe",
      company: "Nom de la compagnie",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip",
      lot: {
        delivry_start_date: "12/02/2020",
        delivry_end_date: "18/02/2020",
        starting_city: "Toulouse",
        starting_postal_code: 75013,
        starting_address: "1, rue de la fontaine à mulard",
        starting_access: "Plein pied",
        arrival_city: "Marseille",
        arrival_postal_code: 13000,
        arrival_address: "3, rue de la sainte",
        arrival_access: "Plein pied",
        size: 54,
        photo_url: "https://picsum.photos/600",
        distance: 1236,
      },
    },
    {
      travel_id: 6,
      owner_uid: "1",
      client_uid: "sqdsqdqsdqsd",
      status: "",
      active: true,
      price: 350,
      service: "Standard",
      company: "Nom de la compagnie",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip",
      lot: {
        delivry_start_date: "12/02/2020",
        delivry_end_date: "18/02/2020",
        starting_city: "Paris",
        starting_postal_code: 75013,
        starting_address: "1, rue de la fontaine à mulard",
        starting_access: "Plein pied",
        arrival_city: "Rouen",
        arrival_postal_code: 13000,
        arrival_address: "3, rue de la sainte",
        arrival_access: "Plein pied",
        size: 60,
        photo_url: "https://picsum.photos/210",
        distance: 1236,
      },
    },
    {
      travel_id: 7,
      owner_uid: "1",
      client_uid: "sqdsqdqsdqsd",
      status: "",
      active: true,
      price: 100,
      service: "Standard",
      company: "Nom de la compagnie",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip",
      lot: {
        delivry_start_date: "12/02/2020",
        delivry_end_date: "18/02/2020",
        starting_city: "Paris",
        starting_postal_code: 75013,
        starting_address: "1, rue de la fontaine à mulard",
        starting_access: "Plein pied",
        arrival_city: "Marseille",
        arrival_postal_code: 13000,
        arrival_address: "3, rue de la sainte",
        arrival_access: "Plein pied",
        size: 28,
        photo_url: "https://picsum.photos/220",
        distance: 1236,
      },
    },
  ],
};
