export const TEAM_DETAILS = {
  data: [
    {
      id: "1",
      coach_firstname: "Fab",
      coach_name: "BOLOSS",
      club_name: "asomba",
      category: "SENIOR",
      competition_level: "D4",
      club_status: "AMATEUR",
      stadium_name: "stade solignat",
      address: "rue jalapa quartier du PLATEAU 94500 champigny sur marne",
      date_match: "29 Mai",
      time_match: "10:00",
      need_arbitre: false,
      disponibility: true,
    },
    {
      id: "2",
      coach_firstname: "Alex",
      coach_name: "CHICO",
      club_name: "A.S. CHAMPIGNY",
      category: "SENIOR",
      competition_level: "D1",
      club_status: "AMATEUR",
      stadium_name: "stade solignat",
      address: "rue jalapa quartier du PLATEAU 94500 champigny sur marne",
      date_match: "3 Juil.",
      time_match: "9:00",
      need_arbitre: true,
      disponibility: true,
    },
    {
      id: "3",
      coach_firstname: "Will",
      coach_name: "SUSHI",
      club_name: "A.S. ST BRICE COURCELLES",
      category: "U14",
      competition_level: "D5",
      club_status: "PRO",
      stadium_name: "stade solignat",
      address: "rue jalapa quartier du PLATEAU 94500 champigny sur marne",
      date_match: "24 Déc.",
      time_match: "10:00",
      need_arbitre: false,
      disponibility: true,
    },
    {
      id: "4",
      coach_firstname: "Ilal",
      coach_name: "CANETTE",
      club_name: "GPE EDUCATION ADAPTATION JEUNES HANDICAPES",
      category: "U20",
      competition_level: "D3",
      club_status: "SEMI-PRO",
      stadium_name: "stade solignat",
      address: "rue jalapa quartier du PLATEAU 94500 champigny sur marne",
      date_match: "10 Oct.",
      time_match: "10:00",
      need_arbitre: true,
      disponibility: true,
    },
    {
      id: "5",
      coach_firstname: "Johnny",
      coach_name: "WAYNE",
      club_name: "AM.LAIQUE CLAIRMARAIS",
      category: "SENIOR",
      competition_level: "D4",
      club_status: "AMATEUR",
      stadium_name: "stade solignat",
      address: "rue jalapa quartier du PLATEAU 94500 champigny sur marne",
      date_match: "17 Oct.",
      time_match: "10:00",
      need_arbitre: false,
      disponibility: true,
    },
    {
      id: "6",
      coach_firstname: "Chasso",
      coach_name: "TREZOR",
      club_name: "STADE DE REIMS",
      category: "U16",
      competition_level: "D6",
      club_status: "AMATEUR",
      stadium_name: "stade solignat",
      address: "rue jalapa quartier du PLATEAU 94500 champigny sur marne",
      date_match: "10 Oct.",
      time_match: "10:00",
      need_arbitre: true,
      disponibility: true,
    },
    {
      id: "7",
      coach_firstname: "Stef",
      coach_name: "PERVERS",
      club_name: "F.C. CHRISTO",
      category: "U18",
      competition_level: "L2",
      club_status: "SEMI-PRO",
      stadium_name: "stade solignat",
      address: "rue jalapa quartier du PLATEAU 94500 champigny sur marne",
      date_match: "12 Nov.",
      time_match: "10:00",
      need_arbitre: true,
      disponibility: true,
    },
    {
      id: "8",
      coach_firstname: "Yannick",
      coach_name: "YOMELAX",
      club_name: "CORMONTREUIL F. C.",
      category: "SENIOR",
      competition_level: "L1",
      club_status: "PRO",
      stadium_name: "stade solignat",
      address: "rue jalapa quartier du PLATEAU 94500 champigny sur marne",
      date_match: "24 Déc.",
      time_match: "10:00",
      need_arbitre: false,
      disponibility: true,
    },
  ],
};
